import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { sanityClient, SanityClient, urlFor } from '../sanity';


export default function Home(props) {

  console.log(props)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>{props.title}</h1>
        <p>
          I'm Avidu from Sri Lanka, this is my web portfolio. i'll post here
          some selected projects.
        </p>
      </div>
    </div>
  );
}


export const getServerSideProps = async () => {
  const query = `
  *[_type == "project"] {
    _id,
    title,
    publishedAt,
    body,
    mainImage,
    slug,
  }`;

  const projects = await sanityClient.fetch(query);

  return {
    props: {
      projects,
    }
  }
};

